type HttpStatusMap = {
    [key: number]: { message: string; color: string };
}

export const httpStatusMap: HttpStatusMap = {
    100: { message: "Continue", color: "text-blue-500" },
    101: { message: "Switching Protocols", color: "text-blue-500" },
    102: { message: "Processing", color: "text-blue-500" },
    103: { message: "Early Hints", color: "text-blue-500" },
  
    200: { message: "OK", color: "text-green-500" },
    201: { message: "Created", color: "text-green-500" },
    202: { message: "Accepted", color: "text-green-500" },
    203: { message: "Non-Authoritative Information", color: "text-green-500" },
    204: { message: "No Content", color: "text-green-500" },
    205: { message: "Reset Content", color: "text-green-500" },
    206: { message: "Partial Content", color: "text-green-500" },
    207: { message: "Multi-Status", color: "text-green-500" },
    208: { message: "Already Reported", color: "text-green-500" },
    226: { message: "IM Used", color: "text-green-500" },
  
    300: { message: "Multiple Choices", color: "text-orange-500" },
    301: { message: "Moved Permanently", color: "text-orange-500" },
    302: { message: "Found", color: "text-orange-500" },
    303: { message: "See Other", color: "text-orange-500" },
    304: { message: "Not Modified", color: "text-orange-500" },
    305: { message: "Use Proxy", color: "text-orange-500" },
    307: { message: "Temporary Redirect", color: "text-orange-500" },
    308: { message: "Permanent Redirect", color: "text-orange-500" },
  
    400: { message: "Bad Request", color: "text-red-500" },
    401: { message: "Unauthorized", color: "text-red-500" },
    402: { message: "Payment Required", color: "text-red-500" },
    403: { message: "Forbidden", color: "text-red-500" },
    404: { message: "Not Found", color: "text-red-500" },
    405: { message: "Method Not Allowed", color: "text-red-500" },
    406: { message: "Not Acceptable", color: "text-red-500" },
    407: { message: "Proxy Authentication Required", color: "text-red-500" },
    408: { message: "Request Timeout", color: "text-red-500" },
    409: { message: "Conflict", color: "text-red-500" },
    410: { message: "Gone", color: "text-red-500" },
    411: { message: "Length Required", color: "text-red-500" },
    412: { message: "Precondition Failed", color: "text-red-500" },
    413: { message: "Payload Too Large", color: "text-red-500" },
    414: { message: "URI Too Long", color: "text-red-500" },
    415: { message: "Unsupported Media Type", color: "text-red-500" },
    416: { message: "Range Not Satisfiable", color: "text-red-500" },
    417: { message: "Expectation Failed", color: "text-red-500" },
    418: { message: "I'm a Teapot", color: "text-red-500" },
    421: { message: "Misdirected Request", color: "text-red-500" },
    422: { message: "Unprocessable Entity", color: "text-red-500" },
    423: { message: "Locked", color: "text-red-500" },
    424: { message: "Failed Dependency", color: "text-red-500" },
    425: { message: "Too Early", color: "text-red-500" },
    426: { message: "Upgrade Required", color: "text-red-500" },
    428: { message: "Precondition Required", color: "text-red-500" },
    429: { message: "Too Many Requests", color: "text-red-500" },
    431: { message: "Request Header Fields Too Large", color: "text-red-500" },
    451: { message: "Unavailable For Legal Reasons", color: "text-red-500" },
  
    500: { message: "Internal Server Error", color: "text-red-700" },
    501: { message: "Not Implemented", color: "text-red-700" },
    502: { message: "Bad Gateway", color: "text-red-700" },
    503: { message: "Service Unavailable", color: "text-red-700" },
    504: { message: "Gateway Timeout", color: "text-red-700" },
    505: { message: "HTTP Version Not Supported", color: "text-red-700" },
    506: { message: "Variant Also Negotiates", color: "text-red-700" },
    507: { message: "Insufficient Storage", color: "text-red-700" },
    508: { message: "Loop Detected", color: "text-red-700" },
    510: { message: "Not Extended", color: "text-red-700" },
    511: { message: "Network Authentication Required", color: "text-red-700" }
  };
  
  